import React, { useState } from 'react';
import { Send, Sparkles, Layout, Eye, Code, RefreshCw } from 'lucide-react';
import { EmailTemplates } from './EmailTemplates';

const EmailEditor = ({ onSend }) => {
    const [subject, setSubject] = useState('');
    const [htmlContent, setHtmlContent] = useState('');
    const [viewMode, setViewMode] = useState('edit'); // 'edit', 'preview'
    const [aiPrompt, setAiPrompt] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);

    const applyTemplate = (key) => {
        const tpl = EmailTemplates[key];
        if (tpl) {
            setSubject(tpl.subject);
            setHtmlContent(tpl.html);
            setViewMode('edit');
        }
    };

    const handleAIGenerate = () => {
        if (!aiPrompt) return;
        setIsGenerating(true);

        // SIMULATED AI GENERATION
        setTimeout(() => {
            const mockGenerated = `
<div style="font-family: Arial, sans-serif; color: #fff; background: #000; padding: 20px;">
  <h2 style="color: #D4AF37; text-transform: uppercase;">${aiPrompt}</h2>
  <p>Here is the content you requested, generated by Print Lab AI.</p>
  <p>We are dedicated to providing the best sonic experience. Use the button below to take action.</p>
  <br/>
  <a href="#" style="background: #D4AF37; color: #000; padding: 10px 20px; text-decoration: none; font-weight: bold;">LEARN MORE</a>
</div>`;
            setHtmlContent(mockGenerated);
            setIsGenerating(false);
        }, 1500);
    };

    return (
        <div className="bg-zinc-950 border border-white/5 rounded-3xl overflow-hidden shadow-2xl flex flex-col h-[800px]">
            {/* Toolbar */}
            <div className="bg-zinc-900 border-b border-white/5 p-4 flex items-center justify-between">
                <div className="flex items-center gap-4">
                    <h3 className="font-display font-bold text-white uppercase tracking-wider flex items-center gap-2">
                        <span className="w-2 h-2 rounded-full bg-gold"></span> AI Email Editor
                    </h3>
                    <div className="h-6 w-px bg-white/10"></div>
                    <div className="flex gap-2">
                        {Object.keys(EmailTemplates).map(key => (
                            <button
                                key={key}
                                onClick={() => applyTemplate(key)}
                                className="px-3 py-1.5 rounded-lg bg-zinc-800 text-[10px] font-bold uppercase tracking-widest text-zinc-400 hover:bg-zinc-700 hover:text-white transition-all border border-white/5 hover:border-white/10"
                            >
                                {EmailTemplates[key].name}
                            </button>
                        ))}
                    </div>
                </div>
                <div className="flex gap-2">
                    <button
                        onClick={() => setViewMode('edit')}
                        className={`p-2 rounded-lg transition-all ${viewMode === 'edit' ? 'bg-indigo-500/10 text-indigo-400' : 'text-zinc-500 hover:text-white'}`}
                        title="Code/Edit"
                    >
                        <Code size={18} />
                    </button>
                    <button
                        onClick={() => setViewMode('preview')}
                        className={`p-2 rounded-lg transition-all ${viewMode === 'preview' ? 'bg-[#00D632]/10 text-[#00D632]' : 'text-zinc-500 hover:text-white'}`}
                        title="Preview"
                    >
                        <Eye size={18} />
                    </button>
                </div>
            </div>

            <div className="flex-1 flex overflow-hidden">
                {/* AI / Input Sidebar */}
                <div className="w-80 bg-zinc-900/50 border-r border-white/5 p-6 flex flex-col gap-6">
                    <div className="space-y-4">
                        <label className="text-[10px] font-black text-zinc-500 uppercase tracking-widest">Email Properties</label>
                        <input
                            placeholder="Subject Line"
                            className="w-full bg-black border border-white/10 rounded-xl p-4 text-white font-bold text-sm focus:border-gold/50 outline-none placeholder:text-zinc-800"
                            value={subject}
                            onChange={e => setSubject(e.target.value)}
                        />
                    </div>

                    <div className="space-y-4 flex-1">
                        <label className="text-[10px] font-black text-gold uppercase tracking-widest flex items-center gap-2">
                            <Sparkles size={12} /> AI Generator
                        </label>
                        <div className="bg-black/50 border border-gold/10 p-4 rounded-2xl relative group">
                            <textarea
                                className="w-full bg-transparent text-white text-sm font-medium outline-none resize-none h-32 placeholder:text-zinc-700"
                                placeholder="Describe what you want to say... (e.g. 'Write a polite reminder about the studio policy change')"
                                value={aiPrompt}
                                onChange={e => setAiPrompt(e.target.value)}
                            />
                            <button
                                onClick={handleAIGenerate}
                                disabled={isGenerating || !aiPrompt}
                                className="absolute bottom-4 right-4 bg-gold text-black p-2 rounded-lg hover:bg-white transition-all disabled:opacity-50 disabled:cursor-not-allowed group-focus-within:shadow-[0_0_20px_rgba(212,175,55,0.2)]"
                            >
                                {isGenerating ? <RefreshCw size={16} className="animate-spin" /> : <Sparkles size={16} />}
                            </button>
                        </div>
                        <p className="text-[10px] text-zinc-600 leading-relaxed">
                            <strong>Tip:</strong> Select a template first, then use AI to rewrite specific sections or generate a fresh intro.
                        </p>
                    </div>

                    <button
                        onClick={() => onSend({ subject, html: htmlContent })}
                        className="w-full bg-indigo-600 text-white py-4 rounded-xl font-black uppercase tracking-widest hover:bg-indigo-500 transition-all shadow-lg active:scale-95 flex items-center justify-center gap-3 group"
                    >
                        <Send size={18} className="group-hover:translate-x-1 transition-transform" /> Send Campaign
                    </button>
                </div>

                {/* Main Content Area */}
                <div className="flex-1 bg-black overflow-y-auto">
                    {viewMode === 'edit' ? (
                        <div className="h-full relative">
                            <textarea
                                className="w-full h-full bg-[#0a0a0a] text-zinc-300 font-mono text-sm p-8 outline-none border-none resize-none"
                                value={htmlContent}
                                onChange={e => setHtmlContent(e.target.value)}
                                placeholder="<!-- HTML Source Code -->"
                            />
                        </div>
                    ) : (
                        <div className="h-full bg-white">
                            <iframe
                                title="preview"
                                srcDoc={htmlContent}
                                className="w-full h-full border-none"
                            />
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};

export default EmailEditor;
